name: CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  check:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v1
      - name: Build with Gradle
        run: |
          ./gradlew clean check --profile